### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by AkinDagba** [AkinDagba/GCMS-Akin-Ferreira#2]
- [ ] o Instalar Git localmente
- [ ] o Criar projeto local
- [ ] o Criar repositório local e realizar commits
- [ ] o Subir alterações para o repositório remoto
- [ ] o Fazer alterações no repositório da turma
@ramidedantas

**Comment by ramidedantas** [comment]
@AkinDagba sugiro editar para tirar esses "bullets" da frente; deve ser de copiar e colar.
